# Generated by Django 4.1.3 on 2022-11-27 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default='Буэнос диас', max_length=255),
        ),
    ]
